version: "3.3"

services:
  db:
    image: mongo:4.4
    container_name: "atsGo_container"
    networks:
      - atsGo
    ports:
      - 27017:27017

  atsGo:
    image: atsgo:1.3.4
    build: .
    environment:
      - ATSGO_SERVER_ADDR=http://alphatree.services
    networks:
      - atsGo
    ports:
      - 80:80
    volumes:
      - atsgocsrvol:/root/csr/
      - atsgokeysvol:/root/keys/
    depends_on:
      - db
      
networks:
  atsGo:

volumes:
  atsgocsrvol:
    driver: local
    driver_opts:
      type: none
      device: /etc/letsencrypt/csr/
      # device: /media/pipi/AMPGOTEST/Data/db
      o: bind
  atsgokeysvol:
    driver: local
    driver_opts:
      type: none
      device: /etc/letsencrypt/keys/
      # device: /media/pipi/AMPGOTEST/Data/db
      o: bind